---
deployment:
  tasks:
    - export DEPLOYPATH=/home/olivqevx/public_html/
    - /bin/cp -R Content $DEPLOYPATH
    - /bin/cp -R CSS $DEPLOYPATH
    - /bin/cp -R HTML $DEPLOYPATH
    - /bin/cp -R Javascript $DEPLOYPATH
    - /bin/cp -R Prism $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH


